server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 932859653002-5f4d0onmunl3d4mskml298jbtqd52p55.apps.googleusercontent.com
            client-secret: pkOe6-jfAZPhbWIrORfdQqOL
            scope:
            - email
            - profile
            
          facebook:
            client-id: 977792446093636
            client-secret: 4773052fa84cf4483e4e14ae3df515b6
            scope:
            - email
            - public_profile
            
          naver:
            client-id: fDK3lSrM5W9HXUII5tdj
            client-secret: M0WHzKQYHs
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
            